[WNMGDS-1141][WNMGDS-1175] Add the ds-healthcare-gov package to the monorepo (#1193)
* Add the ds-healthcare-gov package to the monorepo

There is currently an error during build that seems to have to do with mismatched react types:
```
/Users/patrickwolfert/Projects/design-system/node_modules/@types/react-dom/node_modules/@types/react/index.d.ts(2981,14): error TS2300: Duplicate identifier 'LibraryManagedAttributes'.
```

* [WNMGDS-1141] Update build scripts to support child design systems in monorepo (#1194)

* Make package versions independent of each other in lerna

* Fix build child ds by standardizing the react typdef versions

To test this, rename the cmsds.healthcare.config.js file so that it is the main config file. Prior to these changes, the build step was failing with a typescript error because there were conflicting type definitions. I had to manually delete an entry in yarn.lock in order for this to work.

* Fix the Sass build config to know where to fetch deps

Again, to test this, rename the cmsds.healthcare.config.js file so that it is the main config file. I will update the scripts in a future commit to not require this step

* Add arg to scripts for specifying path to config file

* Add script alias for building hc.gov ds and update config so it works

* Update repository entry in package.json files for monorepo format

* Get rid of nested ternary

* [WNMGDS-1141] Add script for publishing child design systems to GitHub Pages (#1195)

Add a script for publishing child design systems to GH Pages

* [WNMGDS-1175] Update testing scripts to support child design systems in monorepo (#1201)

* Update snapshots for footer logos

* Update reference to a removed icon component

* Update chromedriver

* Added temporary script for running healthcare e2e tests in isolation

* Update snapshot

* Ignore dangerouslySetInnerHTML lint violations in hc.gov cds

* [WNMGDS-1175] Run prettier on ds-healthcare-gov files (#1204)

Run prettier with version that the core uses. Even though their entries in package.json were identical, the hc.gov ds was using prettier 2.2.1, and core was using 2.0.5. This is a change that happened automatically when running `yarn lint`. At some point we'll want to update the version we use in core.

* [WNMGDS-1175] Update browser tests in ds-healthcare-gov (#1206)

* [NO-TICKET] Fix a typo in the prop docs for TextField (#1200)

* [WNMGDS-1133] e2e test cleanup (#1202)

* updated e2e tests files to now be a11y tests

* updating chromedriver for a11y test support

* updating build scripts and documentation

* updating directory naming from e2e to a11y

* seperating Filterchip work into different branch

* add a11y test for Review component

* updates to test config

* Convert hc.gov e2e tests to a11y tests

Co-authored-by: Anna Scheuler Kammeyer <33579665+scheul93@users.noreply.github.com>

* [WNMGDS-1141] Update release scripts (#1208)

* Commit temporary changes

* Create branch prior to `lerna version`

* Compare git hashes before and after version to detect bump

* git branch -D instead of -d

* Use one of the git tags in the example command

* Use the straight tag for publish script instead of version number

* Build healthcare.gov as well

* Zip up the ds-healthcare-gov package as well

* Remove the teeth of the scripts for testing

* Revert "Remove the teeth of the scripts for testing"

This reverts commit fe13e57ff56e7f3c8c98de0fbc643f9d4551eafe.

Co-authored-by: Anna Scheuler Kammeyer <33579665+scheul93@users.noreply.github.com>