Remove generic type in TextInput
It was causing problems and wasn't actually used in the public-facing TextField props anyway. The TextField props extend the props of `input` instead of `input` OR `textarea`, which is wrong but isn't affected by this change.

Here's the error we're getting that this solves:
```
packages/design-system/src/components/TextField/TextField.tsx:186:14 - error TS2322: Type '{ inversed: boolean; id: string; setRef: (elem: HTMLElement) => void; errorId: string; errorMessage: ReactNode; errorPlacement: "top" | "bottom"; dir?: string; form?: string; ... 297 more ...; value?: TextFieldValue; }' is not assignable to type 'IntrinsicAttributes & PropsWithChildren<TextInputProps>'.
  Type '{ inversed: boolean; id: string; setRef: (elem: HTMLElement) => void; errorId: string; errorMessage: ReactNode; errorPlacement: "top" | "bottom"; dir?: string; form?: string; ... 297 more ...; value?: TextFieldValue; }' is not assignable to type '{ ariaLabel?: string; defaultValue?: TextInputDefaultValue; disabled?: boolean; errorId?: string; errorMessage?: ReactNode; errorPlacement?: TextInputErrorPlacement; ... 13 more ...; value?: TextInputValue; }'.
    Types of property 'multiline' are incompatible.
      Type 'boolean' is not assignable to type 'false'.

186             <TextInput
                 ~~~~~~~~~

Found 1 error.
```