Disable typedefs build for Preact for now because class components throw errors
I'm currently at a loss for how to resolve these errors besides converting them all from class components to functional components. Here's a sample of the errors I'm getting:

```
packages/design-system/src/components/Accordion/AccordionItem.tsx(82,10): error TS2339: Property 'state' does not exist on type 'AccordionItem'.
packages/design-system/src/components/Accordion/AccordionItem.tsx(91,12): error TS2339: Property 'props' does not exist on type 'AccordionItem'.
packages/design-system/src/components/Accordion/AccordionItem.tsx(93,12): error TS2339: Property 'setState' does not exist on type 'AccordionItem'.
packages/design-system/src/components/Accordion/AccordionItem.tsx(93,37): error TS2339: Property 'state' does not exist on type 'AccordionItem'.
packages/design-system/src/components/Accordion/AccordionItem.tsx(107,14): error TS2339: Property 'props' does not exist on type 'AccordionItem'.
packages/design-system/src/components/Accordion/AccordionItem.tsx(112,68): error TS2339: Property 'state' does not exist on type 'AccordionItem'.
packages/design-system/src/components/Accordion/AccordionItem.tsx(119,12): error TS2604: JSX element type 'HeadingTag' does not have any construct or call signatures.
packages/design-system/src/components/Accordion/AccordionItem.tsx(136,67): error TS2339: Property 'state' does not exist on type 'AccordionItem'.
packages/design-system/src/components/Autocomplete/Autocomplete.tsx(175,20): error TS2339: Property 'props' does not exist on type 'Autocomplete'.
packages/design-system/src/components/Autocomplete/Autocomplete.tsx(176,25): error TS2339: Property 'props' does not exist on type 'Autocomplete'.
packages/design-system/src/components/Autocomplete/Autocomplete.tsx(198,37): error TS2339: Property 'props' does not exist on type 'Autocomplete'.
```