[WNMGDS-3041] Fix Angular event binding on nested web components (#3327)
* Proof of concept showing the shadow DOM and slots will fix the Angular nested wc issue

Using a `slot` element to pass all children through to the rendered Preact element children retains all Angular event bindings because the browser just reflects all the original elements into the `slot` element magically, like a tunnel.

The next stage of the discovery will be making the shadow DOM an option because we determined that it's not appropriate for all components at this time without major refactors for several of the React components. And we need to determine which components to apply this solution to. The ones I'm thinking of right now are `ds-alert`, `ds-accordion`, `ds-drawer`, `ds-modal-dialog`, `ds-hint`, `ds-inline-error`, `ds-tooltip`, and that might be it. After that we need to figure out how to overcome a11y issues with using the shadow dom as it relates to these specific components, especially `ds-hint`, which is often linked to via `aria-describedby` and can have interactive content (which is why we want to pass that content through via slots).

* Have the two solutions coexist and differentiate with the `shadow: boolean` option

* Enable it on only the `ds-alert` and show event binding failing on `ds-accordion`

Because right now the `shadow` option isn't turned on for `ds-accordion`, which means the Angular events get clobbered by the conversion of children into Preact VirtualDOM

* Nested component event binding works for accordion after turning on `shadow` option

* WIP: Enabled shadow on drawer and dialog but specific slots like `heading` don't work

* Named slots are working on `ds-alert` but not `ds-modal-dialog`

* Fixed `ds-modal-dialog` slots. It was how we defined them in Storybook

You can't make your named slots children of things that go into the default (unnamed) slot. That's a browser thing, not an us thing.

* Fix hyphenated named slots (ds-drawer)

* After writing this comment explaining the "gotchas" of named slots

I'm realizing that there's no reason to recursively check children for named slots, except that we could warn our users if they're using named slots incorrectly! I think I'll change the code to only check for direct children but then also run the recursive check in order to warn users about incorrect usage.

* Warn users when they're using named slots incorrectly

* Be a little more clear about the "why" in the error message

* Enable shadow dom for `ds-review`

* Discovered that slots break the modal's dialog form closing it

The `<form method="dialog">` being provided through a slot and being submitted no longer closes the dialog

* Go back to manually closing the dialog when certain action buttons are clicked

* WIP: Updated Angular example and discovered that named slots don't work in Angular

But dynamically changing the default child content does!

* Fix named slots in Angular

* Handle closing the dialog in the Angular example

* WIP: Fixing unit tests, starting with accordion

* Fix analytics being unable to parse text content from `<slot>` elements

* Update `ds-alert` unit tests

* Side effect of analytics change that actually produces a better result

* WIP: Trying to get `ds-drawer` tests working

* Skipped one drawer test, but the rest are working

* Re-home my generic testing helper

* Make a convenient version of that helper that has baked-in types

* Apply it more consistently to the tests I've fixed so far

* Fix the `ds-review` tests

* Fix dialog tests

* Undo testing library upgrade

* Fix our build system trying to build test helpers outside of Jest

Running `yarn build` was failing with the following errors:

```
packages/design-system/src/components/web-components/testingUtils.tsx(3,17): error TS2742: The inferred type of 'createGenericTestRenderer' cannot be named without a reference to '@testing-library/dom/node_modules/pretty-format/build/types'. This is likely not portable. A type annotation is necessary.

packages/design-system/src/components/web-components/testingUtils.tsx(43,17): error TS2742: The inferred type of 'createTestRenderer' cannot be named without a reference to '@testing-library/dom/node_modules/pretty-format/build/types'. This is likely not portable. A type annotation is necessary.
```

* Update cdn example VRT snapshots (which will be broken until next release)

For now I'm going to update the ones that were just related to the broken inline dialog being rendered in the CDN example, which will be fixed when all these web component updates are released. Because of the slots, the styles changed slightly.

* Simplify redundant conditions and bring the clarity of a constant

* A fix for bordered accordion items

This works, but there's a flash of unstyled content, which isn't nice. I could go back to passing in the parent element to the preact components in `define`, but maybe I can do it selectively.

* Optionally send the custom element to the Preact wrapper so there's no FOUC

* Fix the accordion content first-child/last-child rules in slotted content

* Fix healthcare CSS overrides for accordions in web components

This `.ds-c-accordion` parent in the selector was probably added for increased specificity, but now we can guarantee the cascade order of the theme file and don't need the added specificity. Having that parent in the selector doesn't work when the shadow dom is at play

* Fix the visual regressions in wc examples by applying all heading styles in alert

For some reason the heading styles for alerts didn't use all the properties that base heading styles used, which means without the shadow DOM the heading will be affected by `.ds-content :where(h2)` rules if the `.ds-content` class is somewhere on an ancestor. We won't ever have that ancestor in the Shadow DOM. Let's assume we do want all the normal heading styles going forward

* f907456 was possibly a mistake. 308 VRT refs changed.

We might have to decide between changing our expecation of the alert heading styles for all our "isolated" components and changing our expectation of how `.ds-content` styles get applied to the alert. That is, right now in applications there might be a lot of alerts that are inheriting heading styles from the `ds-content` heading styles. But there could also be cases where they aren't. The fact that the current alert doesn't defend against those styles overriding the alert styles is problematic.

* Fix bug introduced in d5dd5a where the dialog no longer worked

The shadow-dom components weren't getting updates from the signals

* Handle case where no `ds-accordion` ancestor is found

* VRTs for accordion are different with shadow dom

In Storybook, the healthcare styles don't work in the Shadow DOM because they're namespaced (see [this explanation](https://github.com/CMSgov/design-system/pull/3334#issuecomment-2513227970))

* There are now multiple buttons since the dialog action buttons are slotted

* WIP: working on an idea for watching for style changes

Committing what I have, because I need to pivot. I'm finding that it's not the moment when the `<link>` gets added or changed but the moment when the new styles are actually fetched and loaded by the browser that is important.

* Well, this should theoretically work, but it doesn't

Unfortunately several browsers don't seem to actually fire the `load` event. [Here's a blog post about it](https://www.phpied.com/when-is-a-stylesheet-really-loaded/). Might have to switch to a polling solution 🤦

* Poll for changes instead because of inconsistent browser behavior

I'm not poll-crazy, honest. It's the only thing that seems to work (see previous commit message), and it's simple. It's also not enough in our Storybook context to observe changes in the number of stylesheets. In our Storybook, we change the `href` on a `link` element when we change themes instead of adding or removing a link element. That's why I'm taking a "snapshot" of the stylesheets

* Add some doc comments and remove debug logs

* Don't actually need these additional checks with the way I'm using it now

* Updated dialog VRT refs. They all have backdrops!

* This test is actually stable now that we've fixed the CSS race condition in storybook

* Extract changes to individual components and their tests

* Extract changes to non-Angular example projects

* Extract changes to how we find analytics content in our React components

* Extract Angular example changes

* Extract the core changes to preactement that add a shadow dom option

* Extract testing utility modules that were added

* Extract the new module that copies global styles to the shadow dom

* [WNMGDS-3057] Add Shadow DOM capabilities to preactement (#3346)

* Re-apply the core changes to preactement that add a shadow dom option

This reverts commit ec00cc97ad1816c1008ec844f46984d7aa441bec.

* Add a couple basic unit tests for the shadow option of the define function

* Re-add the new module that copies global styles to the shadow dom

This reverts commit a3449c1a6a1fda43bbf54b34742da95f3f3b36b6.

* Use a better variable name here

* [WNMGDS-3057] Update analytics-content-extraction method to support slots (#3347)

* Re-apply changes to how we find analytics content in our React components

This reverts commit 178c7935d9f5e661ca7c960dbac74e4924cb9df8.

* Actually, get rid of the `trim` and undo the one snapshot change

After doing some more testing, this is actually closer to what the browser does naturally, so it's probably better to match that behavior and not mess with the whitespace

* [WNMGDS-3057] Introduce the Shadow DOM to components that need it (#3348)

* Re-add testing utility modules

This reverts commit 031c092332ee35cc2be829c769271819e3a41fbd.

* Re-apply changes to individual components and their tests

This reverts commit 73261e18cfa6bede42f90e36b0056d5c276ef96d.

* Remove snapshot updates for example project

* Added two unit tests, and the second one caught a bug!

Fixed the bug which was that even a value of `boredered="false"` on the `ds-accordion` was being interpreted as truthy because it was a string. Gave the component a new wrapper that parses the boolean. I think it's not happening in Storybook because it uses a boolean control in Storybook and ends up providing the component with a real boolean value in the web component that is rendered by Preact (which is not an expected real-world scenario).

* Trivial change for consistency

* [WNMGDS-3057] Update example projects for Shadow-DOM changes (#3349)

* Re-apply Angular example changes

This reverts commit cc59e6237cfabdc4c13c868e8c49a1e8532c2176.

* Re-apply changes to non-Angular example projects

This reverts commit adc4de60a799fa2c34774ec1c04d804fd17a9f9e.

* Update snapshots for cdn example project

This change is kind of meaningless right now until the changes are released on the CDN, but it keeps the VRTs happy

This reverts commit 77e864a79e313da46bb450e861f5902c54f684d6.