[WNMGDS-2088] Do our own prop-documentation pre-processing (#2296)
* Create a local fork of the `gatsby-transformer-react-docgen` plugin

* None of this works. Saving what I have for future reference

I started gutting this local fork of the plugin and tried to insert the new code from my test script, but I was finding that docgen-typescript wasn't working in that folder. I attempted to get my test script (`docgen.js`) in the `packages/docs` root, but it fails because we use the root `tsconfig.json`, and that configuration is invalid relative to the `packages/docs` directory. We get the following error:

```
Error: TS18003: No inputs were found in config file '../../tsconfig.json'. Specified 'include' paths were '["packages/**/src/**/*"]' and 'exclude' paths were '[]'.
```

* Deleting my local `gatsby-transformer-react-docgen-typescript` plugin

Before pursuing the idea of the transformer plugin, I was thinking the simpler way would be to write a static json file and then just import it in our Gatsby component. It would require one more pre-requisite step to building the doc site, but it wouldn't require a ton of extra code. The other issue is that it'll be a really big file, but actually it's no different from the giant result of the static graphql query done inside the PropTable component right now.

I was doing some exploration into what other design system doc sites do, and Shopify's Polaris seems to compile all the types into a big json file [and then load it from there](https://github.com/Shopify/polaris/blob/ccdcea22ede61858c47a5f4f5f4fde1727f19177/polaris.shopify.com/pages/components/%5Bcomponent%5D.tsx#L118) into whatever website framework they use. So I'm not crazy.

* Starting to integrate the prop data extraction into build script

Ironically this used to be part of the old doc-site-generation scripts. It was using react-docgen, though, and it was very complex and tightly coupled to our doc site generation code

* Committing before I delete some code

My attempt to turn a stream of Vinyl files into a single Vinyl file so it can be piped to `gulp.dest` isn't going well. I don't know the APIs well enough, and I'm just wasting time. I'm just going to use my own writable stream and forget about piping the data along to anything.

* This writes it all to a file, but it's really slow

* Turns out we can actually call parse once with a set of filenames

Maybe I shouldn't even bother doing this with gulp. With the way it is now, the only thing gulp gives me is the globbing, and the streams just complicate things.

* Started deduping component data, and then I realized everything is exported from index

If I just parse the `packages/design-system/src/components/index.ts`, I get all the types that are exported by our design system. There's no need to look at all the individual TS files. That also means we don't need to glob anything, and I might as well cut out the gulp part

* Much simpler, and the output file isn't massive

* Clean up unused files

* Dedupe type data between packages

* Update the doc site code and remove old docgen plugin

* Parse the markdown in the prop docs

* Hide props with the `@hide-prop` directive

* Constants aren't defined in `fs/promises` on older versions of node

* Create data dir if it doesn't exist

* Separate prop-data-extaction into separate command

In order to run `yarn type-check` in the CI job, we had to run the build command for all three design systems, and this would add two minutes to our CI job. I've instead separated the task into its own command and combined all design system props into a single file since we're doing it all at once anyway

* Combining at the parse step simplifies and saves a couple seconds

* Need to also get types for VerticalNavItem, even though we don't export it

Because the VerticalNav page prints a table for VerticalNavItem as a proxy for VerticalNavItemProps

* Run `build:prop-data` when we `yarn build` so we don't have to think about it