[WNMGDS-1871] Migrate unit tests for DateInput to RTL (#2097)
* Need to upgrade deps to avoid some jsdom errors

* Migrate DateInput tests to RTL and make DateInput allow object refs

* Update MultiInputDateField tests as well

* Mocking can fix the errors, but it's not nice

We get errors like this:

```
    Error: Uncaught [Error: `initialFocus` refers to no known node]
        at reportException (/Users/patrickwolfert/Projects/design-system/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
        at Timeout.task [as _onTimeout] (/Users/patrickwolfert/Projects/design-system/node_modules/jsdom/lib/jsdom/browser/Window.js:521:9)
        at listOnTimeout (node:internal/timers:559:17)
        at processTimers (node:internal/timers:502:7) Error: `initialFocus` refers to no known node
        at getNodeForOption (/Users/patrickwolfert/Projects/design-system/node_modules/react-aria-modal/node_modules/focus-trap/index.js:143:15)
        at firstFocusNode (/Users/patrickwolfert/Projects/design-system/node_modules/react-aria-modal/node_modules/focus-trap/index.js:157:9)
        at /Users/patrickwolfert/Projects/design-system/node_modules/react-aria-modal/node_modules/focus-trap/index.js:109:16
        at Timeout.task [as _onTimeout] (/Users/patrickwolfert/Projects/design-system/node_modules/jsdom/lib/jsdom/browser/Window.js:516:19)
        at listOnTimeout (node:internal/timers:559:17)
        at processTimers (node:internal/timers:502:7)
```

I'm finding that if I mock the `focus-trap` module (and its different versions), it'll fix it. However, I think I've just discovered that upgrading `@testing-library/react` even further will fix it.

* Revert "Mocking can fix the errors, but it's not nice"

This reverts commit dd3b635f72aa8cfa704f8216938649c3fb313c37.

* Upgrading RTL even further gets rid of focus-trap errors

I want to add another debugging note before I wrap this up. In the Tooltip implementation file, I was able to put some debug code in the `initialFocus` function which showed that the document was basically empty (an empty `<body>` and `<head>`) whenever it would throw an error. When it didn't throw an error, the document had everything that was expected. I'm glad it was fixed 😅

* Can't share the mock function between tests or it will break