[NO-TICKET] Change the failure threshold for VRT screenshots (#3353)
* Add some interaction test helpers for consistency

* Apply the same helper functions to all the other interaction test modules

* Custom matcher things that don't work

I don't want to have to write a bunch of extra "matcher" code. I just want to return the result of the base `toHaveScreenshot` matcher function, but they don't expose it! If I try to run the solution with `custom-matcher.js`, it will yell thusly:

```
Error: Package subpath './lib/matchers/toMatchSnapshot.js' is not defined by "exports" in /work/node_modules/@playwright/test/package.json
    at new NodeError (node:internal/errors:399:5)
```

If I try to use the one from `expect.ts`, it doesn't like that `baseExpect(page).toHaveScreenshot` returns void. The underlying "matcher" function returns a status object, but when you call `expect(something).theFunction`, it's a void return type.

I think what this all means is that I'm just going to create a helper function instead of extending `expect`. That'll make it a lot clearer in our code that we aren't using the default version

* Revert "Custom matcher things that don't work"

This reverts commit 3b337d7f82f28588202e459ae7963c1755cb7ed3.

* Create an `expectScreenshot` helper and use it everywhere

* Fix unit tests picking up the interaction-test helper module