[NO-TICKET] TypeScript conversions feature branch (#1474)
* [WNMGDS-980] - Convert UsaBanner component to typescript (#1377)

* UsaBanner ts conversion

* forgot exports

* forgot exports

* [WNMGDS-978] tabs typescript conversion (#1382)

* Tabs component conversion to TS

* Tab component conversion to TS

* TabPanel TS conversion

* updated tabs docs & tests

* Converting tab files into functional components

* updated Tab tests

* cleanup

* tab typescript cleanup

* updating Tabs function prop typing

* [WNMGDS-973] - Convert Review component to typescript (#1387)

* review component ts conversion

* using condensed functional style, removing stories from gulp data processing

* condensed format for fragment

* extracting helper function, removing hook use

* docs back to jsx, small typing update

* [WNMGDS-981] verticalnav typescript (#1396)

* Init Typescript conversion.

* Fix verticalnav unit tests.

* Refactor code.

* Update TS types, refactor useEffect and fix subnavToggle tests.

* updated UsaBanner index from js -> ts

* [WNMGDS-972] Convert MonthPicker to TypeScript (#1392)

* A WIP first pass of migrating MonthPicker to TypeScript

* Finished converting MonthPicker to TypeScript

* Update tests so they don't print errors about missing handler functions

* Actually, we don't need to require these. We treat them as optional in the code

* Update file reference

* Remove old type definition file

* reverting react-i18next package back to previous version (#1405)

* clean up TS exports (#1406)

* [WNMGDS-1272] Configure project for type-checking and fix errors (#1445)

* Fix our TypeScript configuration

Changes:
- Only check our src files and not node_modules
- Fix the `@design-system` alias so it knows where to find those files in the docs examples (even though this will not last forever)
- Exclude type checking for our manual TS definitions, because they're messed up

* Add TODO comment

* Add a "yarn type-check" command for convenience

* Fix TS errors in tests that interact with window.utag

* Fix Button test errors by cleaning up Button prop types

The types should now be more accurate.

* Fix errors in DateInput tests and remove obsolete test

* Fix maskHelpers test errors by making parameters optional

They were already being treated as optional, and we were testing for that behavior

* (WIP) Fix last error with ts-ignore, but ts-ignore not allowed by linter

* (WIP) Use generic types to implement attempted fix for last error

But it still doesn't fix it.

* Allow ts-ignore directive, because sometimes we know what we're doing

In certain cases it's not worth the time cost to solve every compiler error and have perfect type-checking

* Revert "(WIP) Use generic types to implement attempted fix for last error"

This reverts commit b5f986571b90338e5ca80d0fb79beb8d7efd8f34.

The original solution is simpler and actually works. We can revisit this error later. In the meantime, we're not changing any of our library's logic, and what I'm doing is logically sound. I just can't get the types to match up right now.

* Fix refactoring mistake in Button unit tests

* Remove obsolete snapshot

That snapshot actually showed that the unit test wasn't working

* Fix unit test console warnings for Button usage

* Fix build warnings for the docs site

* Fix console warnings in the unit tests about TextInput props

* Fix List a11y test

The example moved after 8dfdc3b

* Revert "Fix use of removed function in react-i18next after major version bump"

This reverts commit 82a207b61b55a7c8f8b31e99cb064387cce5fee9.

* Revert "Update reference to i18next `translate` function"

This reverts commit 434163bc7eb5d882101358badb0c1e8485c54825.

* Fix child design system docs examples failing to import

I don't really understand why this change works, but it does. It's unintuitive to me because the `src` folders don't contain any index file or anything

* Ignore errors in doc example TS after config fix

* Revert change of test setup file related to i18next bump

* Ignore storybook-static directory for linting

* [NO-TICKET] Upgrade TypeScript to 4.5.4 (#1452)

* Upgrade to TypeScript 4.5.4

* Trying to fix build error by relocating locale json files

* [WNMGDS-979] - Tooltip/TooltipIcon Typescript conversion (#1451)

* Initial cleanup

* got popper working

* settimeout makes it work somehow, saving for pair analysis

* using refs and useLayoutEffect works

* updated hooks for options

* moved listeners to useeffect

* cleanup, snapshot update

* very small cleanup

* oops this shouldnt be in here

* syntax updates

* dont need these either

* fixing snapshots with ref change

* [NO-TICKET] Upgrade react-i18next again (#1454)

* Revert "reverting react-i18next package back to previous version (#1405)"

This reverts commit 00c347062d1d294260ede5689fec6a3f1f0187a2.

* Revert "Revert "Fix use of removed function in react-i18next after major version bump""

This reverts commit bf5eee3715cce7528eb668b11be93b2903bb3163.

* Revert "Revert "Update reference to i18next `translate` function""

This reverts commit fd1ba16e96a5c3645c59af29cfc320719f957565.

* Revert "Revert change of test setup file related to i18next bump"

This reverts commit 78c44529ed40d955a8ab33e310c3778abf0304ef.

* Fix instance of `translation` HOC

* [WNMGDS-1276] Convert PrivacySettingsDialog to TypeScript (#1461)

* Revert "reverting react-i18next package back to previous version (#1405)"

This reverts commit 00c347062d1d294260ede5689fec6a3f1f0187a2.

* Revert "Revert "Fix use of removed function in react-i18next after major version bump""

This reverts commit bf5eee3715cce7528eb668b11be93b2903bb3163.

* Revert "Revert "Update reference to i18next `translate` function""

This reverts commit fd1ba16e96a5c3645c59af29cfc320719f957565.

* Revert "Revert change of test setup file related to i18next bump"

This reverts commit 78c44529ed40d955a8ab33e310c3778abf0304ef.

* Convert privacySettings.js to TS and add types dependency

* Convert PrivacySettingsTable to TypeScript

* Convert PrivacySettingsDialog to TypeScript

Unfortunately type checks fail because TS finds errors in `node_modules/react-i18next/src/index.d.ts`

* Type-checking works after react-i18next upgrade

* Fix cookie-setting setPrivacySettings function not being called

* Updated unit tests

* skip nav conversion to TS (#1463)

* [WNMGDS-976] Convert StepList component to TypeScript (#1453)

* Convert StepLink to TypeScript

* Convert Step and SubStep to TypeScript, but need TS 4.x features

* Don't need to explicitly define this type with TS 4.5

* Convert StepList to TypeScript

* Convert StepList index file and export types

* Fix StepList story not showing up in Storybook

* onClick handler has never been treated as required, so don't require it

* Don't require substeps either!

* Missed this when updating onClick requirements

* Cleaned out old typedef files

* [WNMGDS-1275] Convert Healthcare Logo component to TypeScript (#1468)

* Convert Logo component to TypeScript

* Remove old typedef file

* Make locale prop optional

* [WNMGDS-969] Typescript Dialog Conversion (#1462)

* first commit, functional switchover

* updated refs, included button types, functional

* small cleanup

* these shouldn't be here

* putting those back

* proper exporting in typescript

* adding ariamodalprops definition for modal

* checking if prettier hits this

* wrapping analytics test event for use with fuctional component

* fixed ordering

* [WNMGDS-1273] Convert Healthcare Footer to TypeScript (#1448)

* Convert HC footer to TS.

* Update TS interfaces for HC footer.

* Update footer and subcomponents to use new i18next API

In order for us to be able to keep our same external API, we're going to have to get creative and use the namespaces feature in a way it wasn't intended. It's a little weird, but it works.

* Update Footer filename in docs

* We actually want to keep this

because it applies to both generated and handmade definitions

* Mock window.scroll for unit tests in setupTests

Co-authored-by: Patrick Wolfert <patrick.wolfert@adhocteam.us>

* [WNMGDS-1121] usabanner refactor ts (#1471)

* applying refactor changes to USA banner

* updated USA banner html example

* resolving doc site build errors

* moving onMediaChange to be scoped with useEffect

* [WNMGDS-1274] Convert Healthcare Header to TypeScript (#1467)

* Init HC header TS conversion.

* Consolidate and type ActionMenu component

* Fix errors. Don't need to type-check unit tests right now

* Fix final error, but document the potential bug that TypeScript has found

* Convert root level i18n.js file to TS and fix some related tests and snapshots

* Update ActionMenu tests after consolidation

And move to `@testing-library/react`

* Fix Header and its unit tests

* Correctly use the ActionMenu's props type and then clean up resulting errors

* Update snapshots of unused prop that was removed

* Reuse Link type definition

* Add missing type annotations

* Remove old Header typedefs

Co-authored-by: zarahzachz <sarah.sachs@gmail.com>

* [WNMGDS-1272] Clean up ds-healthcare-gov types (#1472)

* Use a single `Language` type

* Use a TypeScript entry file for ds-healthcare-gov and fix types as necessary

* Apparently `type` keyword no longer needed and causes errors downstream

* Fix the `Button` type override

It needs to come after the `export * from '@cmsgov/design-system'` in order to override it, and we have to explicitly name the type we want to export from our local Button module

* Well, that didn't work

* Add comment

* Test commit that changes the TS example project

* Revert "Test commit that changes the TS example project"

This reverts commit be7f2fa9231465ed259d21011e3bffcb2c51bbf8.

* Update TS version used in the example to be beyond 3.8

* [WNMGDS-971] Convert Drawer and HelpDrawer to Typescript (#1466)

* Convert Drawer to TS.

* Refactor HelpDrawer to TS.

* Update Drawer to use correct ref

* Updated types in tests and realized toggles didn't have html el props

Was getting this error:
```
packages/design-system/src/components/Drawer/DrawerToggle.test.tsx:52:46 - error TS2345: Argument of type '{ ariaLabel: string; }' is not assignable to parameter of type 'Partial<DrawerToggleProps>'.
  Object literal may only specify known properties, and 'ariaLabel' does not exist in type 'Partial<DrawerToggleProps>'.

52     const { wrapper } = renderDrawerToggle({ ariaLabel });
                                                ~~~~~~~~~
```

* Export all the things

* Whoops, fix unit test

* Forgot that we replace this prop by one with a different name

Co-authored-by: Patrick Wolfert <patrick.wolfert@adhocteam.us>

* [WNMGDS-1272] Clean up core types (#1473)

* Remove src/types directory

* Add nullish return values to getApplicationNode

because all our examples can possibly return null, and even the examples in the `react-aria-modal` documentation can possibly return null

* React.ReactNode seems to be wrong as a return type for function components

Because in the examples/create-react-app-typescript Tooltip example the compiler complains that `<Tooltip`, with a return type of React.ReactNode is not a valid JSX element

* Remove these render function return types too

because they don't appear to be necessary and could cause problems like they did for the functional components

Co-authored-by: Forrest <forrest.baer@adhocteam.us>
Co-authored-by: Anna Kammeyer <scheul93@gmail.com>
Co-authored-by: Anna Scheuler Kammeyer <33579665+scheul93@users.noreply.github.com>
Co-authored-by: Sarah <zarahzachz@users.noreply.github.com>
Co-authored-by: zarahzachz <sarah.sachs@gmail.com>