[WNMGDS-2222][WNMGDS-2224] Build react, preact, and web-components versions of each design system (#2405)
* Base functionality from the discovery branch

* WIP: Reworking gulp tasks to build react, preact, and web-components versions of everything

* Fix task names and bundle preact

* Working through TS errors building typedef files for Preact

Went from `TypeScript: 248 semantic errors` to `TypeScript: 121 semantic errors` by using `require.resolve` for the paths config

* Disable typedefs build for Preact for now because class components throw errors

I'm currently at a loss for how to resolve these errors besides converting them all from class components to functional components. Here's a sample of the errors I'm getting:

```
packages/design-system/src/components/Accordion/AccordionItem.tsx(82,10): error TS2339: Property 'state' does not exist on type 'AccordionItem'.
packages/design-system/src/components/Accordion/AccordionItem.tsx(91,12): error TS2339: Property 'props' does not exist on type 'AccordionItem'.
packages/design-system/src/components/Accordion/AccordionItem.tsx(93,12): error TS2339: Property 'setState' does not exist on type 'AccordionItem'.
packages/design-system/src/components/Accordion/AccordionItem.tsx(93,37): error TS2339: Property 'state' does not exist on type 'AccordionItem'.
packages/design-system/src/components/Accordion/AccordionItem.tsx(107,14): error TS2339: Property 'props' does not exist on type 'AccordionItem'.
packages/design-system/src/components/Accordion/AccordionItem.tsx(112,68): error TS2339: Property 'state' does not exist on type 'AccordionItem'.
packages/design-system/src/components/Accordion/AccordionItem.tsx(119,12): error TS2604: JSX element type 'HeadingTag' does not have any construct or call signatures.
packages/design-system/src/components/Accordion/AccordionItem.tsx(136,67): error TS2339: Property 'state' does not exist on type 'AccordionItem'.
packages/design-system/src/components/Autocomplete/Autocomplete.tsx(175,20): error TS2339: Property 'props' does not exist on type 'Autocomplete'.
packages/design-system/src/components/Autocomplete/Autocomplete.tsx(176,25): error TS2339: Property 'props' does not exist on type 'Autocomplete'.
packages/design-system/src/components/Autocomplete/Autocomplete.tsx(198,37): error TS2339: Property 'props' does not exist on type 'Autocomplete'.
```

* Bundle web components (just one bundle for now)

[We could possibly split web components into separate bundles](https://github.com/CMSgov/design-system/discussions/2378#discussioncomment-5058892), but it would require that we deal with the issue of child design system side effects. Hmm, but now that I think about it, this implementation won't load the child design system side effects either. It won't load component overrides or config settings like default error position.

* Create package exports config for core and remove `.esm.js` renaming logic

The renaming logic doesn't really seem to be necessary. If it were to be anything, I think it should probably be a `.mjs` extension applied to all of the modules being processed, but we currently don't do that, so we probably shouldn't start doing it now.

* Trying to get healthcare to build

* Add example projects to test the react and preact package exports

The "." and "./preact" exports from the package seem to work, but I still get typescript errors when building healthcare that say the web-components module doesn't exist

* When I import instead of export from, I get a much more verbose error

It makes it past the TS/babel compile step, and it fails at the webpack step, where it prints a long error explaining all the places it's looking for the `@cmsgov/design-system/web-components` module, all of which are incorrect. It doesn't seem to follow the `"./web-components":` entry in the core package.json file, and it complains that the "browser" config is blank.

* Revert "When I import instead of export from, I get a much more verbose error"

This reverts commit 0e5d756610dfc545510a302230731249f3d122fd.

* Upgrade to TypeScript 4.9

* TS docs say "types" entry needs to come first, but it doesn't fix it

[Here in the docs](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#packagejson-exports-imports-and-self-referencing) it says that the "types" condition should always come first in "exports". I've also tried putting the fallbacks after "exports". I still get an error when building healthcare that it can't find `@cmsgov/design-system/web-components`

* I can build healthcare!!!

I went back to staring at our tsconfig and looked up the [documentation on the moduleResolution property](https://www.typescriptlang.org/tsconfig#moduleResolution) and discovered that TypeScript won't actually use the ECMAScript Module Support from version 4.7 unless we've set it to `node16` or `nodenext`! No wonder my package.json config wasn't working!

* In order to appease webpack, we needed to use the full path instead of package.json exports path

However, if we `export * from` that full path to the web-components index file, TypeScript doesn't know where to get its type definitions, because the link
to the TS definitions for that entry point were established in that "exports" config in the package.json file, and using the full path circumvents it. Only
by using "import" and the full path do we circumvent both the package.json exports config so webpack works and circumvent type checking so TypeScript works.
 BUT WHEN WE DO THAT, THE COMPONENTS DON'T SHOW UP IN THE ds-healthcare-gov web-components BUNDLE!!!!

* Pretty sure webpack isn't using the package.json exports

I'm pretty sure I've proved that it doesn't use what's in the "exports" config at all because if I remove the following fallbacks, it will not be able to create the base preact bundle either:

```
  "main": "dist/react-components/cjs/index.js",
  "module": "dist/react-components/esm/index.js",
  "types": "dist/react-components/types/index.d.ts",
```

That is, if I comment out `bundleWebComponents` but leave `bundlePreactComponents` in the gulpfile, it will now fail on the first when those fallback paths are not defined.

* Using WebPack 5 fixes everything. (Needed to migrate Storybook to use it too)

* Clean up troubleshooting notes

* Changed import paths in medicare and fixed TypeScript errors

* Update example readmes

* Add cdn examples from the discovery branch

* Add the UsaBanner to web components and make the example more interesting

I wanted to be able to show some of the capabilities for the web components in the `cdn-web-components` example

* Fix TypeScript errors in doc site

Unfortunately in core we don't define a type for the props passed to the actual link components in VerticalNavItemLabel, so for now I've made it use `any` to match core. We were also adding our own stuff to the VerticalNavItemProps, so I made a local version of that type in those doc-site modules

* Update the index of examples

* Fix reference to "React" instead of "Preact" in example

* Fix outdated use of "primary" buttons in examples

* Use globbing pattern instead of listing each file with side effects explicitly