Custom matcher things that don't work
I don't want to have to write a bunch of extra "matcher" code. I just want to return the result of the base `toHaveScreenshot` matcher function, but they don't expose it! If I try to run the solution with `custom-matcher.js`, it will yell thusly:

```
Error: Package subpath './lib/matchers/toMatchSnapshot.js' is not defined by "exports" in /work/node_modules/@playwright/test/package.json
    at new NodeError (node:internal/errors:399:5)
```

If I try to use the one from `expect.ts`, it doesn't like that `baseExpect(page).toHaveScreenshot` returns void. The underlying "matcher" function returns a status object, but when you call `expect(something).theFunction`, it's a void return type.

I think what this all means is that I'm just going to create a helper function instead of extending `expect`. That'll make it a lot clearer in our code that we aren't using the default version