[WNMGDS-1373] Gatsby core doc site (#1897)
* [WNMGDS-1376] initial add of gatsby doc site (#1698)

* gitignore for gatsby setup

* initial add of gatsby doc site

* updated gatsby build commands

* updated gatsby dependency classification to help resolve package version mis-matches

* [NO-TICKET] resolving ts errors unearthed by Gatsby (#1709)

* updated config files for ts resolution due to gatsby

* updated component for ts resolution from gatsby

* Catch cases in `i18n` `translate` where translation is not string

* dependency revert

Co-authored-by: Patrick Wolfert <patrick.wolfert@adhocteam.us>

Co-authored-by: Patrick Wolfert <patrick.wolfert@adhocteam.us>

* [WNMGDS-1582] gatsby docs site frame (#1705)

* gitignore for gatsby setup

* initial add of gatsby doc site

* updated gatsby build commands

* updating header and layout for gatsby doc site

* saving latest release version as environment variable for download

* updated gatsby dependency classification to help resolve package version mis-matches

* adding to lerna ignore

* Update packages/docs/src/components/DocSiteHeader.tsx

Co-authored-by: Patrick Wolfert <patrick.wolfert@adhocteam.us>

* moved react to peer dependency for docs to get  correct version

* removing component aliasing in favor of a ds dependency for docs

* yarn lock update

* remove docs tsconfig

Co-authored-by: Patrick Wolfert <patrick.wolfert@adhocteam.us>

* [WNMGDS-1588] gatsby desktop nav (#1716)

* gitignore for gatsby setup

* initial add of gatsby doc site

* updated gatsby build commands

* updating header and layout for gatsby doc site

* saving latest release version as environment variable for download

* updated gatsby dependency classification to help resolve package version mis-matches

* adding to lerna ignore

* dynamic doc site nav

* renaming content files to support ordering in nav

* nav updates

* delete persistent docs tsconfig

* updated doc site nav graphql query and data formatting

* [NO-TICKET] Allow for a `PATH_PREFIX` env var in the gatsby config (#1734)

* [WNMGDS-1583] Gatsby footer (#1733)

* Publish (#1707)

- @cmsgov/design-system-docs@3.3.0-beta.1
 - @cmsgov/design-system-scripts@3.3.0-beta.1
 - @cmsgov/design-system@3.3.0-beta.1
 - @cmsgov/ds-healthcare-gov@7.3.0-beta.1
 - @cmsgov/ds-medicare-gov@5.3.0-beta.1

* WIP - Implement footer

* Add ability to test local builds on in-network devices.

* Implement and style footer.

* Replace double-quote with single-quote, implement privacy modal.

* Update font-size in feedback section.

* Replace style values with variables.

* Apply PR recommendations.

* changing import for VerticalNavItemProps

Co-authored-by: Forrest Baer <forrest@forrestbaer.com>
Co-authored-by: Anna Kammeyer <scheul93@gmail.com>

* [WNMGDS-1589] gatsby mobile nav (#1739)

* gitignore for gatsby setup

* initial add of gatsby doc site

* updated gatsby build commands

* updating header and layout for gatsby doc site

* saving latest release version as environment variable for download

* updated gatsby dependency classification to help resolve package version mis-matches

* adding to lerna ignore

* dynamic doc site nav

* previous naming convention content files removal

* adding classnames to doc site

* moving github links into reusable component

* mobile nav for gatsby doc site

* adding spacing in footer for mobile nav button

* cleanup

* styling update

* styling updates

* [WNMGDS-1590] info page layout (#1741)

* creating reusable layout page and loading intro data to test info page layout

* creating content renderer component for mdx content coming from graphql

* [WNMGDS-1595] info content migration (#1751)

* creating reusable layout page and loading intro data to test info page layout

* creating content renderer component for mdx content coming from graphql

* moving getting started content

* guidelines content migration

* formatting some markdown elements

* missed content updates

* refactoring helpers

* updated nav linking for content pages

* updated internal links in content files

* updated yarn.lock

* changing file name

* PR updates

* [NO-TICKET] gatsby code snippet formatting (#1755)

* creating reusable layout page and loading intro data to test info page layout

* creating content renderer component for mdx content coming from graphql

* moving getting started content

* guidelines content migration

* formatting some markdown elements

* missed content updates

* refactoring helpers

* updated nav linking for content pages

* updated internal links in content files

* updated yarn.lock

* changing file name

* PR updates

* syntax highlighting using prismjs

* code block formatting on small screens

* adding border to code blocks

* [WNMGDS-1591] prop table (#1771)

* layout max width

* adding doc gen to gatsby

* setting up base prop table ui

* prop table with live data

* updating comments to appease gatsby-mdx-transformer

* make prop table scrollable

* prop table updates

* Update packages/design-system/src/components/TextField/TextInput.tsx

Co-authored-by: Patrick Wolfert <patrick.wolfert@adhocteam.us>

* refactoring props table

Co-authored-by: Patrick Wolfert <patrick.wolfert@adhocteam.us>

* [WNMGDS-1596] Styles > Base content migration (#1789)

* embedded examples and base styles content

* adding prettier to format HTML

* [WNMGDS-1596] styles content migration  (#1791)

* embedded examples and base styles content

* adding prettier to format HTML

* color palette content migration

* spacing content migration

* typography content pt 1

* cleanup

* spacing for color swatch

* [WNMGDS-1596] responsive example (#1801)

* responsive example

* cleanup

* [WNMGDS-1596] utility pages pt1 (#1817)

* responsive example

* cleanup

* utilities pages pt 1

* forgotten files -- woops

* visbility utilities

* flexbox utility page and updates

* cleanup

* fixed visibility stories interpolation

* prettier

* visibility story update

* [WNMGDS-1596] utility pages pt2 (#1820)

* responsive example

* cleanup

* utilities pages pt 1

* forgotten files -- woops

* visbility utilities

* flexbox utility page and updates

* cleanup

* fixed visibility stories interpolation

* utility page content pt 2

* prettier

* updates

* changing  iframe url to be relative

* trying another iframe url for deploys

* [WNMGDS-1596] utility pages pt3 (#1825)

* padding content

* text align content

* text color content

* utility content

* utility content updates

* prettier updates

* moving images out of static resources

* linking updates

* [NO-TICKET] conditional font path for storybook styles (#1839)

* conditional font path for storybook styles

* added images path

* [WNMGDS-1592] storybook example (#1841)

* example for components using storybook

* storybook example updates

* storybook example updates

* [WNMGDS-1592] component page support (#1840)

* support for additional items in page header

* removing showJumpToGuidance frontmatter var and using toc instead

* null checking

* [WNMGDS-1645] component content migration pt 1 (#1844)

* support for additional items in page header

* removing showJumpToGuidance frontmatter var and using toc instead

* accordion component content

* autocomplete content

* alert & badge content

* cleanup

* updates

* updating docs ds dependency

* component content pt 2 (#1855)

* [WNMGDS-1676] component content pt 4 (#1862)

* pulling out view source link into reusable component

* component content

* tabs content

* prettier

* hide props from prop table

* state for vertical nav (#1865)

* [WNMGDS-1598] patterns content (#1872)

* patterns content

* fix capitalization

* ts update

* [WNMGDS-1675] component content pt 3 (#1875)

* component content pt 3

* prettier

* adding max width to text in page content

* text width update

* [WNMGDS-1690] Add CDN Documentation (#1885)

* adding cdn documentation to installation page

* updating typos and order

* oops missed colon

* adding 404 page and associated content along with updating sidebar to exclude new content folder for future use (#1894)

* [NO-TICKET] Merge master into Gatsby branch (#1896)

* merge master into gatsby feature

* Commit yarn.lock updates

* Fix 1 of 2 errors

* Don't need this line anymore

* Remove generic type in TextInput

It was causing problems and wasn't actually used in the public-facing TextField props anyway. The TextField props extend the props of `input` instead of `input` OR `textarea`, which is wrong but isn't affected by this change.

Here's the error we're getting that this solves:
```
packages/design-system/src/components/TextField/TextField.tsx:186:14 - error TS2322: Type '{ inversed: boolean; id: string; setRef: (elem: HTMLElement) => void; errorId: string; errorMessage: ReactNode; errorPlacement: "top" | "bottom"; dir?: string; form?: string; ... 297 more ...; value?: TextFieldValue; }' is not assignable to type 'IntrinsicAttributes & PropsWithChildren<TextInputProps>'.
  Type '{ inversed: boolean; id: string; setRef: (elem: HTMLElement) => void; errorId: string; errorMessage: ReactNode; errorPlacement: "top" | "bottom"; dir?: string; form?: string; ... 297 more ...; value?: TextFieldValue; }' is not assignable to type '{ ariaLabel?: string; defaultValue?: TextInputDefaultValue; disabled?: boolean; errorId?: string; errorMessage?: ReactNode; errorPlacement?: TextInputErrorPlacement; ... 13 more ...; value?: TextInputValue; }'.
    Types of property 'multiline' are incompatible.
      Type 'boolean' is not assignable to type 'false'.

186             <TextInput
                 ~~~~~~~~~

Found 1 error.
```

* Fix last error about optional `type` prop

* multi-input a11y was running wrong example fil

* Put these exported types back until a breaking change

* updated gatsby mdx for single input field

Co-authored-by: Anna Kammeyer <scheul93@gmail.com>
Co-authored-by: Forrest Baer <forrest@forrestbaer.com>

* Revert date field guidance changes

* Switch date field to From Single- to MultiInputDateField

* Restoring healthcare-specific guidance updates

Co-authored-by: Patrick Wolfert <patrick.wolfert@adhocteam.us>
Co-authored-by: Sarah <zarahzachz@users.noreply.github.com>
Co-authored-by: Forrest Baer <forrest@forrestbaer.com>